### ISSUE TITLE
Why don't Google Authenticator Codes Match valid_totp?

### ISSUE THREAD

**Issue by thekantian** [lepture/otpauth#4]
I have manually entered a secret into Google Authenticator on iOS for a time-based code.

I have checked that the time on my server matches the time on my iOS device.

The codes that my iOS device is generating are not accepted as valid by my OtpAuth instance. 

Any ideas what might be wrong here (assuming that I didn't typo the code)? Is anybody else successfully using Google Authenticator for generating valid codes with this library to check them?

**Comment by lepture** [comment]
> I have manually entered a secret into Google Authenticator

Maybe you enter the wrong secret. The app accepts a stripped base64 encoded string. For example:

```python
>>> otp = OtpAuth('secret')
```

You should enter into the App with: `ONSWG4TFOQ`

You can generate the encoded secret with:

```python
>>> otp.to_uri('totp', 'MyLabel', 'OtpAuth')
u'otpauth://totp/MyLabel?secret=ONSWG4TFOQ&issuer=OtpAuth'
```

**Comment by thekantian** [comment]
Thanks so much. This was exactly my issue - the encoding of the secret is not well documented!
